title: "Fiona Roy"
author: "Fiona Roy"
description: "Complexity made simple"
permalink: /posts/:title
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "fiona_roy_cv_technical_writer.pdf", title: "CV"}
  - {title: "Subgraphs", file: "tutorial_excerpt_subgraphs.md"}
  - {title: "Cross-ledger DEXA", file: "overview_excerpt_cross-ledger_dex_aggregator.md"}
  - {title: "Perpetual Contracts", file: "introduction_perpetual_contract_defi.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: "E-mail", icon: envelope, url: "mailto:firoyj@gmail.com"}
  - {title: "GitHub", icon: github, url: "https://github.com/firoyj"}
  - {title: "LinkedIn", icon: linkedin, url: "https://www.linkedin.com/in/fiona-roy-technical-writer/"}
  - {title: "X", icon: twitter, url: "https://twitter.com/Cryptotraduz"}

include:
 - _pages

exclude:
 - _posts
 
comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
